export const aimags = [
    {label: 'Улаанбаатар', value: '1'},
    {label: 'Төв аймаг', value: '2'},
    {label: 'Архангай', value: '3'},
    {label: 'Баянхонгор', value: '4'},
    {label: 'Баян-өлгий', value: '5'},
    {label: 'Булган', value: '6'},
    {label: 'Говь-Алтай', value: '7'},
    {label: 'Говьсүмбэр', value: '8'},
    {label: 'Дархан-Уул', value: '9'},
    {label: 'Дорнод', value: '10'},
    {label: 'Дундговь', value: '11'},
    {label: 'Завхан', value: '12'},
    {label: 'Орхон', value: '13'},
    {label: 'Өвөрхангай', value: '14'},
    {label: 'Өмнөговь', value: '15'},
    {label: 'Сүхбаатар', value: '16'},
    {label: 'Сэлэнгэ', value: '17'},
    {label: 'Увс', value: '18'},
    {label: 'Ховд', value: '19'},
    {label: 'Хөвсгөл', value: '20'},
    {label: 'Хэнтий', value: '21'},
]

export const soums = [
    {label: 'Багануур', value: '101', parent: '1'},
    {label: 'Багахангай', value: '102', parent: '1'},
    {label: 'Баянгол', value: '103', parent: '1'},
    {label: 'Баянзүрх', value: '104', parent: '1'},
    {label: 'Налайх', value: '105', parent: '1'},
    {label: 'Сонгинохайрхан', value: '106', parent: '1'},
    {label: 'Сүхбаатар', value: '107', parent: '1'},
    {label: 'Хан-Уул', value: '108', parent: '1'},
    {label: 'Чингэлтэй', value: '109', parent: '1'},
    {label: 'Цэцэрлэг', value: '301', parent: '3'},
    {label: 'Батцэнгэл', value: '302', parent: '3'},
    {label: 'Булган', value: '303', parent: '3'},
    {label: 'Жаргалант', value: '304', parent: '3'},
    {label: 'Ихтамир', value: '305', parent: '3'},
    {label: 'Өгийнуур', value: '306', parent: '3'},
    {label: 'Өлзийт', value: '307', parent: '3'},
    {label: 'Өндөр-Улаан', value: '308', parent: '3'},
    {label: 'Тариат', value: '309', parent: '3'},
    {label: 'Төвшрүүлэх', value: '310', parent: '3'},
    {label: 'Хайрхан', value: '311', parent: '3'},
    {label: 'Хангай', value: '312', parent: '3'},
    {label: 'Хашаат', value: '313', parent: '3'},
    {label: 'Хотонт', value: '314', parent: '3'},
    {label: 'Цахир', value: '315', parent: '3'},
    {label: 'Цэнхэр', value: '316', parent: '3'},
    {label: 'Чулуут', value: '317', parent: '3'},
    {label: 'Эрдэнэбулган', value: '318', parent: '3'},
    {label: 'Эрдэнэмандал', value: '319', parent: '3'},
]